package web;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.EventListener;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.socket.messaging.SessionConnectedEvent;
import org.springframework.web.socket.messaging.SessionDisconnectEvent;

import search.GatewayInterface;
import search.Search;

@Controller
public class WebController {

    private GatewayInterface gateway = null;
    private Thread statisticsThread;
    private volatile boolean running = false;

    @Autowired
    private GeminiService geminiService;

    @Autowired
    private HackerNewsService hackerNewsService;

    @Autowired
    private SimpMessagingTemplate messagingTemplate;

    private int activeWebSocketSessions = 0;

    public WebController() {
        gateway = connectToGateway();
    }

    @EventListener
    public synchronized void handleWebSocketConnectListener(SessionConnectedEvent event) {
        System.out.println("Client connected via WebSocket.");
        activeWebSocketSessions++;
        System.out.println("Active Web Sockets: " + activeWebSocketSessions);

        if (!running) {
            running = true;
            statisticsThread = new Thread(() -> {
                List<String> previousStats = null;
                while (running) {
                    try {
                        List<String> currentStats = gateway.getFormattedStatistics();

                        if (previousStats == null || !previousStats.equals(currentStats)) {
                            messagingTemplate.convertAndSend("/topic/statistics", currentStats);
                            previousStats = currentStats;
                        }

                        Thread.sleep(1000);
                    } catch (RemoteException e) {
                        System.out.println("Error communicating with the Gateway. Attempting to reconnect...");
                        gateway = connectToGateway();
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        System.out.println("Statistics thread interrupted.");
                    }
                }
            });
            statisticsThread.start();
        }
    }

    @EventListener
    public synchronized void handleWebSocketDisconnectListener(SessionDisconnectEvent event) {
        System.out.println("Client disconnected from WebSocket.");
        activeWebSocketSessions--;

        if (activeWebSocketSessions <= 0) {
            running = false;
            if (statisticsThread != null && statisticsThread.isAlive()) {
                statisticsThread.interrupt();
            }
        }
    }

    // Redirects to the main page
    @GetMapping("/")
    public String redirect() {
        return "redirect:/greetings";
    }

    // Home page
    @GetMapping("/greetings")
    public String principal() {
        return "greetings";
    }

    // Page displaying the search results and the text generated by Gemini
    @GetMapping("/search")
    public String buscar(@RequestParam(name = "query", required = false, defaultValue = "") String query,
                         @RequestParam(name = "page", defaultValue = "1") int page, Model model) {
        String AItext = geminiService.generateText(query);
        try {
            List<Search> result_search = gateway.makeSearch(query, page);
            boolean hasNextPage = result_search.size() > 0;

            model.addAttribute("textoIA", AItext);
            model.addAttribute("result", result_search);
            model.addAttribute("hasNextPage", hasNextPage);
            model.addAttribute("query", query);
            model.addAttribute("page", page);

            if (!hasNextPage) {
                model.addAttribute("noMoreResults", "No further results");
            }

            return "search";
        } catch (RemoteException e) {
            System.out.println("Error communicating with the Gateway. Attempting to reconnect...");
            gateway = connectToGateway();
        }
        return "search";
    }

    // Page that performs the indexing function of a website placed in the input
    @GetMapping("/indexing")
    public String inserir(@RequestParam(name = "query", required = false, defaultValue = "Empty") String query, Model model) throws RemoteException {
        try {
            String result = gateway.proccessUrl(query);
            model.addAttribute("result", result);
            return "indexing";
        } catch (RemoteException e) {
            System.out.println("Error communicating with the Gateway. Attempting to reconnect...");
            gateway = connectToGateway();
        }
        return "indexing";
    }

    // Page dedicated to presenting statistics via web socket
    @GetMapping("/statistics")
    public String estatisticas() {
        return "statistics";
    }

    // Page dedicated to presenting websites that link to a website specified in the input
    @GetMapping("/specificurl")
    public String buscarUrl(@RequestParam(name = "query", required = false, defaultValue = "") String query, Model model) {
        try {
            List<String> result_busca = gateway.getUrlList(query);
            model.addAttribute("result", result_busca);
            return "specificurl";
        } catch (RemoteException e) {
            System.out.println("Error communicating with the Gateway. Attempting to reconnect...");
            gateway = connectToGateway();
        }
        return "specificurl";
    }

    // Page dedicated to the results of data obtained by the HackerNews API
    @GetMapping("/hacker")
    public String hacker(@RequestParam(name = "query", required = false, defaultValue = "") String query, Model model) {
        try {
            List<HackerNewsResult> items = hackerNewsService.fetchTopStories(query);
            for (HackerNewsResult item : items) {
                String response = gateway.proccessUrl(item.getUrl());
                item.setGatewayResponse(response);
            }
            model.addAttribute("result", items);
        } catch (RemoteException e) {
            System.out.println("Error communicating with the Gateway. Attempting to reconnect...");
            gateway = connectToGateway();
        }
        return "hacker";
    }

    // Function dedicated to maintaining the connection with the Gateway in case of a connection problem
    private static GatewayInterface connectToGateway() {
        GatewayInterface gateway = null;
        while (gateway == null) {
            try {
                gateway = (GatewayInterface) LocateRegistry.getRegistry(8183).lookup("gateway");
                System.out.println("Connected to the Gateway!");
            } catch (RemoteException | NotBoundException e) {
                System.out.println("Gateway offline... Trying again in 2 seconds...");
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ie) {
                    System.out.println("Error while attempting to reconnect: " + ie.getMessage());
                    ie.printStackTrace();
                }
            }
        }
        return gateway;
    }
}
